### ISSUE TITLE
Switch dolt function calls from SELECT to CALL

### ISSUE THREAD

**Issue by noamross** [ecohealthalliance/doltr#41]
See https://www.dolthub.com/blog/2022-04-29-select-isnt-sensible/

**Comment by n8layman** [comment]
This is the list of procedures where we'll likely need to switch from 'select' to 'call'

https://docs.dolthub.com/sql-reference/version-control/dolt-sql-procedures

**Comment by n8layman** [comment]
Fixed by PR https://github.com/ecohealthalliance/doltr/pull/63
